---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 06.12.22 14:45
---
function filename(level)
    local str = debug.getinfo(level or 2, "S").source:sub(2)
    return str:match("^.*/(.*).lua$") or str
end

function superfilename()
    return filename(3)
end

function fileInfo()
    local file = superfilename()
    print("Init ".. file)
    return file  .. ': '
end

function keyInfo(description)
    return superfilename() .. ": " .. description
end
