---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 16.12.22 22:54
---
function hotkeybindmodal(mod, key, description, pressedFn, releasedFn)
    local ks = hs.hotkey.modal.new(
            mod,
            key,
            description);

    function ks:entered()
        debugInfo("Start Modal Mode for ".. description)
        pressedFn()
    end
    function ks:exited()
        releasedFn()
        debugInfo("Exit Modal Mode for ".. description)
    end

    ks:bind('', 'escape', "~~~~~hide~~~~~", function() ks:exit() end)
    ks:bind(mod, key, description, function() ks:exit() end)
    return ks
end
