---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 24.04.23 11:09
---

function HotkeyBindSafe(mods, key, message, pressedfn, releasedfn, repeatfn)

    local hotkeyHandler

    hotkeyHandler = hs.hotkey.bind(
            mods,
            key,
            message,
            function ()
                if (pressedfn == nil ) then return end
                hotkeyHandler:disable()
                pressedfn()
                hotkeyHandler:enable()
            end,
            function ()
                if (releasedfn == nil ) then return end
                hotkeyHandler:disable()
                releasedfn()
                hotkeyHandler:enable()

            end,
            function ()
                if (repeatfn == nil ) then return end
                hotkeyHandler:disable()
                repeatfn()
                hotkeyHandler:enable()
            end
    )
    end
