---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 24.04.23 11:09
---

function HotkeyBindSafe(mods, key, message, pressedfn, releasedfn, repeatfn)

    local hotkeyHandler

    hotkeyHandler = hs.hotkey.bind(
            mods,
            key,
            message,
            function ()
                if (pressedfn == nil ) then return end
                hotkeyDisableSilent(hotkeyHandler)
                pressedfn()
                hotkeyEnableSilent(hotkeyHandler)
            end,
            function ()
                if (releasedfn == nil ) then return end
                hotkeyDisableSilent(hotkeyHandler)
                releasedfn()
                hotkeyEnableSilent(hotkeyHandler)
            end,
            function ()
                if (repeatfn == nil ) then return end
                hotkeyDisableSilent(hotkeyHandler)
                repeatfn()
                hotkeyEnableSilent(hotkeyHandler)
            end
    )
    end
