---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 03.08.23 00:47
---

function hotkeybindcycle(modifier, key, message, callbackMap)
    local currentIndex = 1
    local maxIndex = #callbackMap
    local hotkeyHandler
    hotkeyHandler = hs.hotkey.bind(modifier, key, message, function()
        callbackMap[currentIndex]()
        currentIndex = (currentIndex % maxIndex) + 1
    end)
end