---
--- Generated by Luanalysis
--- Created by fueling
--- DateTime: 12.07.22 02:07
--- https://github.com/fuelingtheweb/fuelingzsh/blob/200de21c40ea9a2a09731a6cffa00775c577dc67/dotfiles/.hammerspoon/Helpers/Table.lua


local Table = {}
Table.__index = Table

function Table.has(table, needle)
    for k, v in ipairs(table) do
        if v == needle then
            return true
        end
    end

    return false
end

function Table.count(table)
    if not table then return 0 end

    local count = 0

    Table.each(table, function()
        count = count + 1
    end)

    return count
end

function Table.each(table, callback)
    for key, value in pairs(table) do
        callback(value, key)
    end
end

function Table.assign(t1, t2)
    if t2 == nil then return t1 end
    for key, value in pairs(t2) do
        t1[key] = value
    end

    return t1
end

function Table.assigned(t1, t2)
    local new = { }
    for key, value in pairs(t1) do
        new[key] = value
    end
    if t2 == nil then return new end
    for key, value in pairs(t2) do
        new[key] = value
    end
    return new
end

return Table