---
--- Generated by Luanalysis
--- Created by fueling
--- DateTime: 12.07.22 02:07
--- https://github.com/fuelingtheweb/fuelingzsh/blob/200de21c40ea9a2a09731a6cffa00775c577dc67/dotfiles/.hammerspoon/Helpers/Table.lua

table.sorted = function(tab, func)
    local tab = {table.unpack(tab)}
    table.sort(tab, func)
    return tab
end

local Table = {}
Table.__index = Table

function Table.has(table, needle)
    for k, v in ipairs(table) do
        if v == needle then
            return true
        end
    end

    return false
end

function Table.count(table)
    if not table then return 0 end

    local count = 0

    Table.each(table, function()
        count = count + 1
    end)

    return count
end

function Table.each(table, callback)
    for key, value in pairs(table) do
        callback(value, key)
    end
end

return Table