---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 07.04.23 11:26
--- https://github.com/mtarbit/dotfiles/blob/master/source/.hammerspoon/util.lua

function readFile(path)
    local f = io.open(path, 'r')
    local s = f:read('a')
    f:close()
    return s
end

function partial(fn, arg)
    return function(...)
        return fn(arg, ...)
    end
end

-- usage:
-- template([[
--   var name = "{{ action }}";
-- ]], {value=(value and 1 or 0)})

function template(s, t)
    local pattern = '{{%s*([^}]-)%s*}}'
    local replace = function(k) return tostring(t[k]) end
    local result, _ = s:gsub(pattern, replace)
    return result
end

function readFileTemplate(path, t)
    return template(readFile(path), t)
end

function runJavaScript(code)
    debugInfo("JS: ", code)
    return hs.osascript.javascript(code)
end

function runAppleScript(code)
    debugInfo("AS: ", code)
    return hs.osascript.applescript(code)
end

