---
--- Generated by Luanalysis
--- Created by fueling.
--- DateTime: 12.07.22 02:09
--- https://github.com/fuelingtheweb/fuelingzsh/blob/master/dotfiles/.hammerspoon/Helpers/Window.lua

local Window = {}
Window.__index = Window

local windows = {}

-- source: https://github.com/fuelingtheweb/fuelingzsh/blob/master/dotfiles/.hammerspoon/Helpers/String.lua#L8-L10
local function strContains(needle, haystack)
    return string.find(haystack, needle)
end

function Window.titleContains(needle)
    return strContains(needle:gsub('-', '%%-'), Window.title())
end

function Window.pathContains(needle)
    return strContains(needle:gsub('-', '%%-'), Window.path())
end

function Window.path()
    return Window.title():match('~%S+')
end

function Window.title()
    return Window.focused():title()
end

function Window.focused()
    return hs.window.frontmostWindow()
end

function Window.openWithCache(name, callback)
    local window = windows[name]

    if window and window:isVisible() and strContains(name, window:title():lower()) then
        return window:focus()
    end

    callback()

    hs.timer.doAfter(0.5, function()
        windows[name] = hs.window.frontmostWindow()
    end)
end

return Window