---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 16.12.22 20:41
--- source: https://github.com/dbalatero/dotfiles/blob/master/hammerspoon/audio-switcher.lua
---
fileInfo()

local function getDeviceChoices()
    local devices = hs.audiodevice.allOutputDevices()

    local choices = {}

    currentUid = hs.audiodevice.current(false).uid
    -- 🔘⚪
    -- ☐☑
    for i, device in ipairs(devices) do
        icon = '🔊'
        if device:outputMuted() then
            icon = '🔇'
        end

        local subText = icon

        if device:outputVolume() then
            subText = subText .. ' Volume ' .. math.floor(device:outputVolume()) .. '%'
        end

        choices[i] = {
            text =  ( currentUid == device:uid() and "➜ " or "    ") .. device:name(),
            subText = "    " .. subText,
            uuid = device:uid(),
        }
    end

    return choices
end

local function handleAudioChoice(choice)
    if not choice then
        return
    end

    local device = hs.audiodevice.findDeviceByUID(choice['uuid'])
    device:setDefaultOutputDevice()
    device:setOutputMuted(false)

    hs.alert('Switched to ' .. choice['text'])
end

----------

local audioChooser = hs.chooser.new(handleAudioChoice)
audioChooser:width(40)

hs.hotkey.bind(hyper, '1',keyInfo("Audio Switcher"), function()
    local choices = getDeviceChoices()

    audioChooser:choices(choices)
    audioChooser:show()
end)