---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 17.12.22 14:05
--- source: https://github.com/johngrib/hammerspoon_caffein/blob/master/hammerspoon_caffein.lua

local caffeine = hs.menubar.new()

local obj = {}

local on_message = 'Caffeine: ON'
local off_message = 'Caffeine: OFF'

local on_icon = "☕️🙄"
local off_icon = "😴"

function obj:init(mod, key, description)

    function setCaffeineDisplay(state)
        if state then
            hs.alert.show(on_message)
            caffeine:setTitle(on_icon)
            caffeine:setTooltip(on_message)
            debugInfo(on_message)
        else
            hs.alert.show(off_message)
            caffeine:setTitle(off_icon)
            caffeine:setTooltip(off_message)
            debugInfo(off_message)
        end
    end

    function caffeineClicked()
        setCaffeineDisplay(hs.caffeinate.toggle("displayIdle"))
    end

    if caffeine then
        caffeine:setClickCallback(caffeineClicked)
        setCaffeineDisplay(hs.caffeinate.get("displayIdle"))
    end

    hs.hotkey.bind(mod, key, description, caffeineClicked)
end

obj:init(hyper, 'c', keyInfo("toggle Caffeine"))

return obj