---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 06.08.22 14:47
---

fileInfo()

KSheet = hs.loadSpoon('KSheet');

--hs.hotkey.bind(
--        hyper,
--        "C",
--        keyInfo("KSheet"),
--        function()
--            KSheet:toggle();
--        end
--);

hotkeybindmodal(
        hyper,
        "x",
        keyInfo("KSheet"),
        function()  KSheet:show() end,
        function() KSheet:hide() end
);

HKSheet = hs.loadSpoon('HotKeySheet');

hotkeybindmodal(
        hyper,
        "a",
        keyInfo("HotKeySheet"),
        function() HKSheet:show() end,
        function() HKSheet:hide() end
);


--local showHotkeys = hs.hotkey.showHotkeys(hyper, 'x')

local FuzzyMatcher = require("Helpers.FuzzyMatcher")

hs.hotkey.bind(hyper, "s", keyInfo("Show help"),
        function()
            local last_win = hs.window.focusedWindow()
            local keys     = hs.hotkey.getHotkeys()

            local chooser_cbk = function(selection)
                if last_win ~= nil then
                    last_win:focus() -- focus last window
                end
            end

            local help = { }
            for i = 1,#keys do
                table.insert(help, {
                    --text = keys[i].msg,
                    text = hs.styledtext.new(keys[i].msg),
                    --subText = hs.styledtext.new('a little text')
                    subText = 'a little text'
                })
            end

            chooser = hs.chooser.new(chooser_cbk)
            --chooser:choices(help)

            FuzzyMatcher.setChoices(help, chooser, false, nil)

            chooser:queryChangedCallback(function()
                FuzzyMatcher.setChoices(help, chooser, false, nil)
            end)

            --chooser:rows(#help)
            chooser:rows(15)
            chooser:width(40)
            --chooser:bgDark(true)
            --chooser:fgColor(hs.drawing.color.x11.orange)
            --chooser:subTextColor(hs.drawing.color.x11.chocolate)
            chooser:show()
        end)
