---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 06.08.22 14:47
---

fileInfo()

KSheet = hs.loadSpoon('KSheet');

--hs.hotkey.bind(
--        hyper,
--        "C",
--        keyInfo("KSheet"),
--        function()
--            KSheet:toggle();
--        end
--);

hotkeybindmodal(
        hyper,
        "c",
        keyInfo("KSheet"),
        function()  KSheet:show() end,
        function() KSheet:hide() end
);

HKSheet = hs.loadSpoon('HotKeySheet');

hotkeybindmodal(
        hyper,
        "a",
        keyInfo("HotKeySheet"),
        function() HKSheet:show() end,
        function() HKSheet:hide() end
);


local showHotkeys = hs.hotkey.showHotkeys(hyper, 'x')
