---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 06.08.22 14:47
---

fileInfo()

KSheet = hs.loadSpoon('KSheet');

hs.hotkey.bind(
--{"option",'shift'},
        hyper,
        "C",
        keyInfo("KSheet"),
        function()
            KSheet:toggle();
        end
);