---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 05.08.22 12:02
---
--- Open New Chrome Window with the same size

fileInfo()

bindHotkey(to("Google Chrome"), { "cmd"}, "n", keyInfo("New Window (only in Chrome)"), function()

    local menuItemName = "Neues Fenster"

    local currentFrame = hs.window.focusedWindow():frame()
    local app = hs.application.frontmostApplication()

    app:selectMenuItem(menuItemName)

    hs.window.focusedWindow():setFrame(currentFrame)

end)