---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 05.08.22 12:02
---

print("init ChromeTabToNewWindow")
hs.hotkey.bind(hyper, "t", function()
    local app = hs.application.frontmostApplication()
    print(app:name())
    if app:name() == "Google Chrome" then
        local menuItemName = "Tab in ein neues Fenster verschieben"
        -- local menuItem = app:findMenuItem(menuItemName)
        -- print(menuItem)
        -- if menuItem.isEnabled then

        --print(hs.inspect.inspect(app:getMenuItems()))

        --hs.application.frontmostApplication():getMenuItems(function(result)
        --  print(string.format("result: %s", hs.inspect(result)))
        --end)

        --hs.application.get("Safari"):selectMenuItem({"Safari", "About Safari"})
        --hs.application.get("Safari"):selectMenuItem({"Safari", "Über Safari"})

        local currentFrame = hs.window.focusedWindow():frame()
        app:selectMenuItem(menuItemName)
        hs.window.focusedWindow():setFrame(currentFrame)

        hs.alert.show("Move tab to new window")

    else
        hs.alert.show("Move tab to new window: not in Chrome - whe are in ".. app:name())
    end
end )