---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 06.08.22 16:11
---

function isConsoleOpen()
    local hspoon = hs.application.applicationsForBundleID(hs.processInfo.bundleID)[1]
    local conswin = hspoon:mainWindow()
    return conswin and true or false
end

local windowHolder
hs.hotkey.bind({ "cmd", "alt", "ctrl" }, "r", function()
    local hspoon = hs.application.applicationsForBundleID(hs.processInfo.bundleID)[1]
    local conswin = hspoon:mainWindow()
    if conswin and hspoon:isFrontmost() then
        conswin:close()
        if windowHolder and #windowHolder:role() ~= 0 then
            windowHolder:becomeMain():focus()
        end
        windowHolder = nil
    else
        windowHolder = window.frontmostWindow()
        hs.openConsole()
    end
end, nil)
