---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 02.08.23 19:51
---

fileInfo()

hs.hotkey.bind(hyper, "d", keyInfo("Type current Date"), function()

    local currentDate = os.date("%Y-%m-%d")
    hs.eventtap.keyStrokes(currentDate)

end )