---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 28.01.23 23:50
---

local scriptInfo = fileInfo()

-- Define a variable to store the MailMate bundle ID
local mailMateCondition =  {"MailMate","essages%)$"}
local whatsAppCondition = {"WhatsApp", "WhatsApp"}

-- Disable the Cmd + W shortcut in Mailmate's viewer window
bindHotkey(toAppsAndTabs(mailMateCondition, whatsAppCondition),{"cmd"}, "W", keyInfo("disable cmd+w on MailMate and WhatsApp"), function()
    -- noop
    debugInfo("ignore shortcut cmd+w on MailMate or WhatsApp in main view")
end)