---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 03.08.23 00:56
---

require("Helpers.HotkeyBindCycle")

fileInfo()

hotkeybindcycle(hyper, "v", keyInfo("Cycle abc"), {
    function() print("a") end,
    function() print("b") end,
    function() print("c") end,
})

hotkeybindcycle(hyper, "b", keyInfo("Cycle defg"), {
    function() print("d") end,
    function() print("e") end,
    function() print("f") end,
    function() print("g") end,
})
