---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 24.04.23 10:32
---

HotkeyBindSafe(hyper, '[', keyInfo("CMD + ["), function()
    hs.eventtap.keyStroke({"cmd"}, "[")
end)

HotkeyBindSafe(hyper, ']', keyInfo("CMD + ]"), function()
    hs.eventtap.keyStroke({"cmd"}, "]")
end)
