---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 14.12.22 19:49
---

fileInfo()


hs.hotkey.bind(hyper, "0", keyInfo("Zoom on/off"),function()
    debugInfo("test")
    hs.eventtap.keyStroke({"cmd","alt"}, "0")
end)

hs.hotkey.bind(hyper, "-", keyInfo("Zoom -"),function()
    debugInfo("test")
    hs.eventtap.keyStroke({"cmd","alt"}, "-")
end)

hs.hotkey.bind(hyper, "=", keyInfo("Zoom +"),function()
    debugInfo("test")
    hs.eventtap.keyStroke({"cmd","alt"}, "=")
end)

