---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 28.01.23 23:50
---

local scriptInfo = fileInfo()

-- Define a variable to store the MailMate bundle ID
local mailmateName = "MailMate"

-- Disable the Cmd + W shortcut in Mailmate's viewer window
bindHotkey(toAppAndTab(mailmateName,"essages%)$"),{"cmd"}, "W", keyInfo("disable cmd+w on MailMate"), function()
    -- noop
    debugInfo("ignore shortcut on mailmate in messages")
end)