---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 06.08.22 14:42
---


-- Recursive Binder: https://apple.stackexchange.com/questions/416588/create-emacs-style-keychains-keybindings-in-hammerspoon

maximizeshortcut = hs.hotkey.bind({"cmd"}, "x", "Maximize", function()
    local win = hs.window.focusedWindow()
    local app = win:application()

    -- local appName = app:name()

    -- to lower case: name:lower()

    local appName = hs.application.frontmostApplication():name()
    hs_hotkey_bind_to({"WhatsApp", "Code"}, nix, "function")

    -- hs_hotkey_bind_to(nix({"WhatsApp", "Code"}), nix, "function")

    -- if appName == "WhatsApp" then
    --   hs.alert.show("minimize app ".. app:name() )
    --   maximizeshortcut:disable()
    --   hs.eventtap.keyStroke({"cmd"}, "m")
    --   maximizeshortcut:enable()
    -- else
    --   win:maximize()
    --   hs.alert.show("maximized app ".. app:name() )
    -- end
    hs.alert.show("done. ".. app:name() )
end )
