---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 05.08.22 11:54
---

print("Init Maximize App")

local maximizeApp = function()
                      local win = hs.window.focusedWindow()
                      local app = win:application()
                      win:maximize()
                      hs.alert.show("maximized app ".. app:name() )
                    end
hs.hotkey.bind({"cmd"}, "m", "Maximize App", maximizeApp )
hs.hotkey.bind(hyper, "m", "Maximize App",  maximizeApp )

