---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 05.08.22 11:54
---

fileInfo()

local maximizeApp = function()
                      local win = hs.window.focusedWindow()
                      local app = win:application()
                      win:maximize()
                      hs.alert.show("maximized app ".. app:name() )
                    end
hs.hotkey.bind({"cmd"}, "m", keyInfo("Maximize App"), maximizeApp )
hs.hotkey.bind(hyper, "m", keyInfo("Maximize App"),  maximizeApp )

