---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 18.12.22 07:40
--- source: https://github.com/JJGO/dotfiles/blob/master/mac/.hammerspoon/multidisplay-black.lua

-- Hyper+F11 toggles black boxes on secondary monitors

fileInfo()

movieblocks = nil

local function blackOff()
    for k, v in pairs(movieblocks) do
        v:delete()
    end
    movieblocks = nil
end

function blackOn(all)
    p = hs.screen.primaryScreen()
    movieblocks = {}
    for k, v in pairs(hs.screen.allScreens()) do
        if v:name() ~= p:name() or all == true then
            max = v:fullFrame()
            box = hs.drawing.rectangle(hs.geometry.rect(max.x, max.y, max.w, max.h))
            black = {["red"]=0,["blue"]=0,["green"]=0,["alpha"]=1.0}
            box:setStrokeColor(black)
            box:setFillColor(black)
            box:setFill(true)
            box:show()
            -- v:setBrightness(0.0)
            movieblocks[k] = box
        end
    end

end

function toggleMovieMode(all)
    if movieblocks ~= nil then
        blackOff()
        for k, v in pairs(hs.screen.allScreens()) do
            v:setBrightness(0.3)
        end
    else
        blackOn(all)
        for k, v in pairs(hs.screen.allScreens()) do
            v:setBrightness(1)
        end
    end
end

function blackOnAll()
    blackOn(true)
end

function  toggleMovieModeAll()
    toggleMovieMode(true)
end


--hs.hotkey.bind(hyper, "2", keyInfo("toggle other display black"),toggleMovieMode)
--hs.hotkey.bind(hyper, "3", keyInfo("toggle all display black"),toggleMovieModeAll)

hotkeybindmodal(
        hyper,
        "2",
        keyInfo("toggle other display black"),
        function() blackOn() end,
        function() blackOff() end
);

hotkeybindmodal(
        hyper,
        "3",
        keyInfo("toggle all displays black"),
        function() blackOnAll() end,
        function() blackOff() end
);


