---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 06.08.22 14:48
---

fileInfo()

hs.hotkey.bind(hyper, "r", keyInfo("Resize all child windows"), function()
    local win = hs.window.focusedWindow()
    local app = win:application()
    local currentFrame = win:frame()
    local wins = app:allWindows()
    for _, childwin in ipairs(wins) do
        childwin:setFrame(currentFrame)
    end

    hs.alert.show("set all childs to same size in app ".. app:name() )
end )
