---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 05.08.22 12:00
---

print("Init Umlauts")

local umlauts = {
    -- note: leave the space before ä Ä - otherwise it not work
    { 'a', ' ä', ' Ä' },
    { 'o', 'ö', 'Ö' },
    { 'u', 'ü', 'Ü' },
    { 'e', '€', '€' },
}

hs.fnutils.each(umlauts, function(umlaut)

    local key,small,big = table.unpack(umlaut)

    hs.hotkey.bind({'alt'}, key, "Umlauts ".. small, function () hs.eventtap.keyStrokes(small) end)
    hs.hotkey.bind({'alt','shift'}, key, "Umlauts ".. big, function () hs.eventtap.keyStrokes(big) end)
end)