---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 05.08.22 12:00
---

print("Init Umlauts")

hs.hotkey.bind({'alt'}, 'u', function ()
    hs.eventtap.keyStrokes('ü')
end)

hs.hotkey.bind({'shift', 'alt'}, 'u', function ()
    hs.eventtap.keyStrokes('Ü')
end)

hs.hotkey.bind({'alt'}, 'a', function ()
    hs.eventtap.keyStrokes(' ä')
end)

hs.hotkey.bind({'shift', 'alt'}, 'a', function ()
    hs.eventtap.keyStrokes(' Ä')
end)

hs.hotkey.bind({'alt'}, 'o', function ()
    hs.eventtap.keyStrokes('ö')
end)

hs.hotkey.bind({'shift', 'alt'}, 'o', function ()
    hs.eventtap.keyStrokes('Ö')
end)

-- Euro

hs.hotkey.bind({'alt'}, 'e', function ()
    hs.eventtap.keyStrokes('€')
end)