---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 20.07.22 08:34
---

fileInfo()

hs.hotkey.bind({"alt","shift"}, "h", keyInfo("Vimperator"), function() hs.hints.windowHints() end)
hs.hints.style = "vimperator"
