---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 20.07.22 08:34
---

hs.hotkey.bind({"alt","shift"}, "h", "Vimperator", function() hs.hints.windowHints() end)
hs.hints.style = "vimperator"
