---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 02.07.23 00:11
---

-- How to install the Spooninstall:
--   - download the zip from https://www.hammerspoon.org/Spoons/SpoonInstall.html
--   - in finder go to your download folder
--   - double click the zip file to unzip
--   - double click on the SpoonInstall.spoon to "automatic" install the spoon into hammerspoon

hs.loadSpoon("SpoonInstall")
Install = spoon.SpoonInstall

function myCommand()
    print("do my commands...")
end

Install:andUse("WiFiTransitions",
        {
            config = {
                actions = {
                    {
                        -- Test action just to see the SSID transitions
                        -- This action fires everytime because it has no `from` and no `to`

                        fn = function(_, _, prev_ssid, new_ssid)
                            local infoText = string.format("From '%s' to '%s'", prev_ssid, new_ssid)
                            hs.notify.show("SSID change", infoText, "")
                            print("SSID change", infoText, "")
                        end
                    },
                    {
                        -- this action run when it leaves the 'iPhone' Wifi
                        from = "iPhone",
                        fn = function(_, _, prev_ssid, new_ssid)
                            local infoText = string.format("From '%s' to '%s'", prev_ssid, new_ssid)
                            hs.notify.show("from iPhone: SSID change", infoText, "")
                            print("from iPhone: SSID change", infoText, "")
                            myCommand()
                        end
                    },
                },
                -- add this to get both action with from=nil and with to=nil
                actOnNilTransitions = true,
            },

            -- start the spoon
            start = true,

            -- remove this line to get no debug infos
            loglevel = "debug"

        }
)