---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 02.07.23 00:11
---

-- download Spooninstall unzip and double click on the SpoonInstall.spoon

hs.loadSpoon("SpoonInstall")
Install = spoon.SpoonInstall

Install:andUse("WiFiTransitions",
        {
            config = {
                actions = {
                    { -- Test action just to see the SSID transitions
                        fn = function(_, _, prev_ssid, new_ssid)
                            hs.notify.show("SSID change", string.format("From '%s' to '%s'", prev_ssid, new_ssid), "")
                            print("SSID change", string.format("From '%s' to '%s'", prev_ssid, new_ssid), "")
                        end
                    },
                    { -- Test action just to see the SSID transitions
                        from = "iPhone",
                        fn = function(_, _, prev_ssid, new_ssid)
                            hs.notify.show("SSID change", string.format("From '%s' to '%s'", prev_ssid, new_ssid), "")
                            print("iPhone: SSID change", string.format("From '%s' to '%s'", prev_ssid, new_ssid), "")
                        end
                    },
                },
                actOnNilTransitions = true,
            },
            start = true,
            loglevel = "debug"

        }
)