---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 06.08.22 14:49
---

fileInfo()

hs.loadSpoon("MiroWindowsManager")

--spoon.MiroWindowsManager.sizes = { 6/5, 4/3, 3/2, 2/1, 3/1, 4/1, 6/1 }
--spoon.MiroWindowsManager.fullScreenSizes = {1, 6/5, 4/3, 2}

-- duration already set in main init
--hs.window.animationDuration = 0.3
spoon.MiroWindowsManager:bindHotkeys({
    up = {hyper, "up"},
    right = {hyper, "right"},
    down = {hyper, "down"},
    left = {hyper, "left"},

    -- disable this keys because other screenshots already do this
    --fullscreen = nil,
    --nextscreen = nil
    fullscreen = {hyper, "f"},
    nextscreen = {hyper, "1"},
    middle = {hyper, "2"}
})


hs.hotkey.bind(hyper, '[', keyInfo("move to left Screen"), function() hs.window.focusedWindow():moveOneScreenWest(true, true) end)
hs.hotkey.bind(hyper, ']', keyInfo("move to right Screen"), function() hs.window.focusedWindow():moveOneScreenEast(true, true) end)
