---
--- Generated by Luanalysis
--- Created by muescha.
--- DateTime: 06.08.22 14:49
---

print("Init WindowManager")


hs.loadSpoon("MiroWindowsManager")
debugInfo(hyper)
hs.window.animationDuration = 0.3
spoon.MiroWindowsManager:bindHotkeys({
    up = {hyper, "up"},
    right = {hyper, "right"},
    down = {hyper, "down"},
    left = {hyper, "left"},

    -- disable this keys because other screenshots already do this
    --fullscreen = nil,
    --nextscreen = nil
    fullscreen = {hyper, "."},
    nextscreen = {hyper, "/"}
})


hs.hotkey.bind(hyper, '[', function() hs.window.focusedWindow():moveOneScreenWest(true, true) end)
hs.hotkey.bind(hyper, ']', function() hs.window.focusedWindow():moveOneScreenEast(true, true) end)
